#!/usr/bin/env bash
# Accepts a string as an argument
# If no argumane; displays ....
# ping the IP 5 times
if [ "$1" == "" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi
