#!/usr/bin/env bash
# displays no from 1 to 100
# displays fizzbuzz when no is mutiple of 3 and 5
# displays fizz when no is multiple of 3
# displays buzz when no is multiple of 5

for num in {1..100}
do
    if (( num % 3 == 0 && num % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( num % 3 == 0 ))
    then
        echo "Fizz"
    elif (( num % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$num"
    fi
done
