#!/usr/bin/env bash
# display 'best school' 10 times and Hi on 9th iteraton

counter=1
while [ $counter -le 10 ]
do
    echo "Best School"
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    fi
    counter=$(( counter + 1 ))
done
