#!/usr/bin/env bash
# loops from 1 to 10
# displays bad luck for 4th loop, good luck for 8th loop
# and Best School for others

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    counter=$(( counter + 1 ))
done
