#!/usr/bin/env bash
# displays numbers from 1 to 20
# displays bad luck from from china for 4th iteration
# displays back luck from japan for 9th iteration
# displays bad luck from italy for 17th iteration

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    case $counter in
        4) echo "bad luck from China";;
        9) echo "bad luck from Japan";;
        17) echo "bad luck from Italy";;
    esac
    counter=$(( counter + 1 ))
done
